### ISSUE TITLE
TypeError: patches.compatiblePackages is not iterable

### ISSUE THREAD

**Issue by TheRedNet** [inotia00/rvx-builder#115]
**Describe the bug**
Failure after download of dependencies

**To Reproduce**

1. Change source organization to 'ReVanced'
2. Click on 'StartPatching'
3. Wait for dependency download to finish
4. Click 'Continue'
5. See error

**Screenshots**
![image](https://github.com/inotia00/rvx-builder/assets/45996791/c1617771-a91e-473a-9394-4f3fb6e1ed83)

**revanced-builder Version:** v3.9.15

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 22H2 (Build 22621.2283)

**Comment by ntcong** [comment]
looks like revanced-patches changed missing patch options from empty array to null which broke patch iteration in several places.

**Comment by auanasgheps** [comment]
I have the same issue, let's wait for the maintainer to comment.

**Comment by inotia00** [comment]
fixed in [rvx-builder-v3.10.0](https://github.com/inotia00/rvx-builder/releases/tag/v3.10.0)

**Comment by auanasgheps** [comment]
As usual, thank you for your fast response!

**Comment by auanasgheps** [comment]
Hi, I have updated to builder v3.10 but I'm still getting the error: 
![image](https://github.com/inotia00/rvx-builder/assets/20586878/6b5fb9c2-30e0-4e8b-9924-e996b7d34fe9)

**Comment by inotia00** [comment]
ah, the reason I closed this issue is because the same issue was reproduced in the RVX patch using CLI v4.0 and I fixed it.
(i.e. I solved the issue in the RVX patch)

Compatibility with official ReVanced sources is not guaranteed

**Comment by ntcong** [comment]
I can confirm it's working for revanced sources, the above comment probably left something not upgraded.

**Comment by inotia00** [comment]
tbh I don't use the official ReVanced source
Since some people seem to want it, I added compatibility with the official ReVanced source in [rvx-builder-v3.10.1](https://github.com/inotia00/rvx-builder/releases/tag/v3.10.1)
